"""Dependency-free domain kernel for DataMind Core 1.0."""
from .budget import Budget, Usage
from .context import ExecutionContext
from .effects import (
    EffectLevel,
    EffectSpec,
    effect_violations,
    require_effect_allowed,
)
from .errors import (
    ArtifactIntegrityError,
    ArtifactNotFoundError,
    BudgetExceeded,
    EffectPolicyError,
    ExecutionError,
    IdempotencyConflictError,
    KernelError,
    KernelValidationError,
    PlanValidationError,
    ReplayError,
    ScopePolicyError,
    SerializationError,
    SnapshotUnavailableError,
    SourceExecutionError,
    SyncError,
    TraceConflictError,
    TraceError,
    TraceNotFoundError,
    UnsupportedSyncError,
    VersionConflictError,
)
from .lifecycle import (
    ArtifactChange,
    ArtifactManifest,
    ArtifactRef,
    ChangeKind,
    ChangeSet,
    SnapshotSet,
    SyncReceipt,
    sha256_checksum,
)
from .memory import (
    EvidenceRef,
    MemoryConflict,
    MemoryKind,
    MemoryLink,
    MemoryLinkKind,
    MemoryRecord,
    ScopeKind,
    ScopeRef,
)
from .provenance import Provenance
from .source import SourceDescriptor
from .trace import ExecutionTrace, TraceEvent, TraceEventKind
from .types import (
    JsonObject,
    JsonScalar,
    JsonValue,
    SnapshotRef,
    SourceKind,
    SourceRef,
    freeze_json,
    freeze_json_object,
    new_id,
    require_aware,
    thaw_json,
    utc_now,
)

__all__ = [
    "ArtifactChange",
    "ArtifactIntegrityError",
    "ArtifactManifest",
    "ArtifactNotFoundError",
    "ArtifactRef",
    "Budget",
    "BudgetExceeded",
    "ChangeKind",
    "ChangeSet",
    "EffectLevel",
    "EffectPolicyError",
    "EffectSpec",
    "EvidenceRef",
    "ExecutionContext",
    "ExecutionError",
    "ExecutionTrace",
    "IdempotencyConflictError",
    "JsonObject",
    "JsonScalar",
    "JsonValue",
    "KernelError",
    "KernelValidationError",
    "MemoryConflict",
    "MemoryKind",
    "MemoryLink",
    "MemoryLinkKind",
    "MemoryRecord",
    "PlanValidationError",
    "Provenance",
    "ReplayError",
    "SerializationError",
    "ScopeKind",
    "ScopePolicyError",
    "ScopeRef",
    "SnapshotRef",
    "SnapshotSet",
    "SnapshotUnavailableError",
    "SourceDescriptor",
    "SourceExecutionError",
    "SourceKind",
    "SourceRef",
    "SyncError",
    "SyncReceipt",
    "TraceConflictError",
    "TraceError",
    "TraceEvent",
    "TraceEventKind",
    "TraceNotFoundError",
    "UnsupportedSyncError",
    "Usage",
    "VersionConflictError",
    "effect_violations",
    "freeze_json",
    "freeze_json_object",
    "new_id",
    "require_effect_allowed",
    "require_aware",
    "sha256_checksum",
    "thaw_json",
    "utc_now",
]
