"""Typed, two-phase state transitions for governed Memory writes."""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional, Tuple, Union

from .errors import KernelValidationError
from .memory import (
    EvidenceRef,
    MemoryKind,
    MemoryLink,
    MemoryLinkKind,
    MemoryOrigin,
    MemoryOriginChannel,
    ScopeKind,
    ScopeRef,
)
from .types import (
    JsonObject,
    SnapshotRef,
    SourceKind,
    SourceRef,
    freeze_json_object,
    require_aware,
    utc_now,
)


class MemoryMutationKind(str, Enum):
    """Semantic state changes; physical erasure is intentionally absent."""

    ASSERT = "assert"
    SUPERSEDE = "supersede"
    RETRACT = "retract"

    def __str__(self) -> str:
        return self.value


def _validate_valid_interval(
    valid_from: Optional[datetime],
    valid_to: Optional[datetime],
) -> None:
    for name, value in (
        ("valid_from", valid_from),
        ("valid_to", valid_to),
    ):
        if value is not None:
            if not isinstance(value, datetime):
                raise KernelValidationError(
                    "{} must be a datetime".format(name)
                )
            require_aware(value, name)
    if (
        valid_from is not None
        and valid_to is not None
        and valid_from >= valid_to
    ):
        raise KernelValidationError(
            "valid interval must be half-open and non-empty"
        )


def _validate_assertion_payload(
    *,
    content: str,
    evidence: Tuple[EvidenceRef, ...],
    links: Tuple[MemoryLink, ...],
) -> Tuple[Tuple[EvidenceRef, ...], Tuple[MemoryLink, ...]]:
    if not isinstance(content, str) or not content.strip():
        raise KernelValidationError(
            "memory assertion content must be a non-empty string"
        )
    evidence = tuple(evidence)
    links = tuple(links)
    if any(not isinstance(item, EvidenceRef) for item in evidence):
        raise KernelValidationError(
            "memory assertion evidence must contain EvidenceRef values"
        )
    if len({item.evidence_id for item in evidence}) != len(evidence):
        raise KernelValidationError(
            "memory assertion evidence cannot contain duplicate ids"
        )
    if any(not isinstance(item, MemoryLink) for item in links):
        raise KernelValidationError(
            "memory assertion links must contain MemoryLink values"
        )
    if len(set(links)) != len(links):
        raise KernelValidationError(
            "memory assertion links cannot contain duplicates"
        )
    if any(
        item.kind is MemoryLinkKind.SUPERSEDES for item in links
    ):
        raise KernelValidationError(
            "SUPERSEDES links are generated by the mutation runtime"
        )
    return evidence, links


@dataclass(frozen=True)
class AssertMemory:
    """Append an independent semantic assertion."""

    kind: MemoryKind
    content: str
    valid_from: Optional[datetime] = None
    valid_to: Optional[datetime] = None
    evidence: Tuple[EvidenceRef, ...] = ()
    links: Tuple[MemoryLink, ...] = ()
    metadata: JsonObject = field(default_factory=freeze_json_object)

    action: MemoryMutationKind = field(
        default=MemoryMutationKind.ASSERT,
        init=False,
    )

    def __post_init__(self) -> None:
        if not isinstance(self.kind, MemoryKind):
            raise KernelValidationError(
                "asserted memory kind must be a MemoryKind"
            )
        _validate_valid_interval(self.valid_from, self.valid_to)
        evidence, links = _validate_assertion_payload(
            content=self.content,
            evidence=self.evidence,
            links=self.links,
        )
        object.__setattr__(self, "evidence", evidence)
        object.__setattr__(self, "links", links)
        object.__setattr__(
            self,
            "metadata",
            freeze_json_object(self.metadata),
        )


@dataclass(frozen=True)
class SupersedeMemory:
    """Close one current assertion and append its explicit replacement."""

    target_id: str
    content: str
    valid_from: Optional[datetime] = None
    valid_to: Optional[datetime] = None
    evidence: Tuple[EvidenceRef, ...] = ()
    links: Tuple[MemoryLink, ...] = ()
    metadata: JsonObject = field(default_factory=freeze_json_object)

    action: MemoryMutationKind = field(
        default=MemoryMutationKind.SUPERSEDE,
        init=False,
    )

    def __post_init__(self) -> None:
        if (
            not isinstance(self.target_id, str)
            or not self.target_id.strip()
        ):
            raise KernelValidationError(
                "supersede target_id must be a non-empty string"
            )
        _validate_valid_interval(self.valid_from, self.valid_to)
        evidence, links = _validate_assertion_payload(
            content=self.content,
            evidence=self.evidence,
            links=self.links,
        )
        if any(item.target_id == self.target_id for item in links):
            raise KernelValidationError(
                "supersede target relation is generated by the runtime"
            )
        object.__setattr__(self, "evidence", evidence)
        object.__setattr__(self, "links", links)
        object.__setattr__(
            self,
            "metadata",
            freeze_json_object(self.metadata),
        )


@dataclass(frozen=True)
class RetractMemory:
    """Close one current assertion without erasing its history."""

    target_id: str
    reason: str
    evidence: Tuple[EvidenceRef, ...] = ()

    action: MemoryMutationKind = field(
        default=MemoryMutationKind.RETRACT,
        init=False,
    )

    def __post_init__(self) -> None:
        for name in ("target_id", "reason"):
            value = getattr(self, name)
            if not isinstance(value, str) or not value.strip():
                raise KernelValidationError(
                    "retract {} must be a non-empty string".format(name)
                )
        object.__setattr__(self, "evidence", tuple(self.evidence))
        if any(
            not isinstance(item, EvidenceRef) for item in self.evidence
        ):
            raise KernelValidationError(
                "retract evidence must contain EvidenceRef values"
            )
        if (
            len({item.evidence_id for item in self.evidence})
            != len(self.evidence)
        ):
            raise KernelValidationError(
                "retract evidence cannot contain duplicate ids"
            )


MemoryChange = Union[AssertMemory, SupersedeMemory, RetractMemory]


@dataclass(frozen=True)
class MemoryMutationDraft:
    """Untrusted semantic intent; it has no authority to change state."""

    scope: ScopeRef
    changes: Tuple[MemoryChange, ...]
    idempotency_key: str
    approval_key: Optional[str] = None

    def __post_init__(self) -> None:
        if not isinstance(self.scope, ScopeRef):
            raise KernelValidationError(
                "memory mutation scope must be a ScopeRef"
            )
        object.__setattr__(self, "changes", tuple(self.changes))
        if not self.changes:
            raise KernelValidationError(
                "memory mutation requires at least one change"
            )
        if any(
            not isinstance(
                item,
                (AssertMemory, SupersedeMemory, RetractMemory),
            )
            for item in self.changes
        ):
            raise KernelValidationError(
                "memory mutation contains an unsupported change"
            )
        targets = tuple(
            item.target_id
            for item in self.changes
            if isinstance(item, (SupersedeMemory, RetractMemory))
        )
        if len(set(targets)) != len(targets):
            raise KernelValidationError(
                "memory mutation cannot target a record more than once"
            )
        if (
            not isinstance(self.idempotency_key, str)
            or not self.idempotency_key.strip()
        ):
            raise KernelValidationError(
                "memory mutation idempotency_key must be non-empty"
            )
        if self.approval_key is not None:
            if (
                not isinstance(self.approval_key, str)
                or not self.approval_key.strip()
            ):
                raise KernelValidationError(
                    "memory mutation approval_key must be non-empty"
                )


def memory_write_requires_approval(
    origin: MemoryOrigin,
    scope: ScopeRef,
) -> bool:
    """Return the fixed first-version write-governance decision."""

    if not isinstance(origin, MemoryOrigin):
        raise KernelValidationError(
            "memory write origin must be a MemoryOrigin"
        )
    if not isinstance(scope, ScopeRef):
        raise KernelValidationError(
            "memory write scope must be a ScopeRef"
        )
    return (
        origin.channel is not MemoryOriginChannel.USER_EXPLICIT
        or scope.kind in (ScopeKind.WORKSPACE, ScopeKind.ORGANIZATION)
    )


@dataclass(frozen=True)
class MemoryMutationProposal:
    """Validated intent bound to one source snapshot and write authority."""

    proposal_id: str
    source: SourceRef
    base_snapshot: SnapshotRef
    draft: MemoryMutationDraft
    origin: MemoryOrigin
    requires_approval: bool

    def __post_init__(self) -> None:
        if (
            not isinstance(self.proposal_id, str)
            or not self.proposal_id.strip()
        ):
            raise KernelValidationError(
                "memory proposal_id must be a non-empty string"
            )
        if not isinstance(self.source, SourceRef):
            raise KernelValidationError(
                "memory proposal source must be a SourceRef"
            )
        if self.source.kind is not SourceKind.MEMORY:
            raise KernelValidationError(
                "memory proposal source must have MEMORY kind"
            )
        if not isinstance(self.base_snapshot, SnapshotRef):
            raise KernelValidationError(
                "memory proposal base_snapshot must be a SnapshotRef"
            )
        if self.base_snapshot.source != self.source:
            raise KernelValidationError(
                "memory proposal snapshot belongs to another source"
            )
        if not isinstance(self.draft, MemoryMutationDraft):
            raise KernelValidationError(
                "memory proposal draft must be a MemoryMutationDraft"
            )
        if not isinstance(self.origin, MemoryOrigin):
            raise KernelValidationError(
                "memory proposal origin must be a MemoryOrigin"
            )
        if self.origin.channel is MemoryOriginChannel.IMPORTED:
            raise KernelValidationError(
                "runtime mutation proposals cannot use imported authority"
            )
        if not isinstance(self.requires_approval, bool):
            raise KernelValidationError(
                "memory proposal requires_approval must be boolean"
            )
        required = memory_write_requires_approval(
            self.origin,
            self.draft.scope,
        )
        if required and not self.requires_approval:
            raise KernelValidationError(
                "memory proposal weakens mandatory approval policy"
            )
        if self.draft.approval_key and not self.requires_approval:
            raise KernelValidationError(
                "memory proposal cannot ignore its declared approval_key"
            )
        if self.requires_approval and not self.draft.approval_key:
            raise KernelValidationError(
                "governed memory proposal requires an approval_key"
            )


@dataclass(frozen=True)
class MemoryMutationReceipt:
    """Auditable outcome of one atomic, idempotent Memory transition."""

    proposal_id: str
    idempotency_key: str
    scope: ScopeRef
    origin: MemoryOrigin
    previous_snapshot: SnapshotRef
    snapshot: SnapshotRef
    created_ids: Tuple[str, ...] = ()
    closed_ids: Tuple[str, ...] = ()
    reused: bool = False
    reversible: bool = True
    applied_at: datetime = field(default_factory=utc_now, compare=False)

    def __post_init__(self) -> None:
        for name in ("proposal_id", "idempotency_key"):
            value = getattr(self, name)
            if not isinstance(value, str) or not value.strip():
                raise KernelValidationError(
                    "memory receipt {} must be non-empty".format(name)
                )
        if not isinstance(self.scope, ScopeRef):
            raise KernelValidationError(
                "memory receipt scope must be a ScopeRef"
            )
        if not isinstance(self.origin, MemoryOrigin):
            raise KernelValidationError(
                "memory receipt origin must be a MemoryOrigin"
            )
        for name in ("previous_snapshot", "snapshot"):
            if not isinstance(getattr(self, name), SnapshotRef):
                raise KernelValidationError(
                    "memory receipt {} must be a SnapshotRef".format(name)
                )
        if self.previous_snapshot.source != self.snapshot.source:
            raise KernelValidationError(
                "memory receipt snapshots must share one source"
            )
        object.__setattr__(self, "created_ids", tuple(self.created_ids))
        object.__setattr__(self, "closed_ids", tuple(self.closed_ids))
        for name in ("created_ids", "closed_ids"):
            values = getattr(self, name)
            if any(
                not isinstance(item, str) or not item.strip()
                for item in values
            ):
                raise KernelValidationError(
                    "memory receipt {} must contain non-empty ids".format(
                        name
                    )
                )
            if len(set(values)) != len(values):
                raise KernelValidationError(
                    "memory receipt {} must be unique".format(name)
                )
        if set(self.created_ids) & set(self.closed_ids):
            raise KernelValidationError(
                "memory receipt cannot create and close the same record"
            )
        for name in ("reused", "reversible"):
            if not isinstance(getattr(self, name), bool):
                raise KernelValidationError(
                    "memory receipt {} must be boolean".format(name)
                )
        if not isinstance(self.applied_at, datetime):
            raise KernelValidationError(
                "memory receipt applied_at must be a datetime"
            )
        require_aware(self.applied_at, "memory receipt applied_at")


__all__ = [
    "AssertMemory",
    "MemoryChange",
    "MemoryMutationDraft",
    "MemoryMutationKind",
    "MemoryMutationProposal",
    "MemoryMutationReceipt",
    "RetractMemory",
    "SupersedeMemory",
    "memory_write_requires_approval",
]
